//회원가입
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

//로그인
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

//로그아웃
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

//내정보 가져오기
export const LOAD_ME_REQUEST = 'LOAD_ME_REQUEST';
export const LOAD_ME_SUCCESS = 'LOAD_ME_SUCCESS';
export const LOAD_ME_FAILURE = 'LOAD_ME_FAILURE';

//닉네임 변경
export const EDIT_NICKNAME_REQUEST = 'EDIT_NICKNAME_REQUEST';
export const EDIT_NICKNAME_SUCCESS = 'EDIT_NICKNAME_SUCCESS';
export const EDIT_NICKNAME_FAILURE = 'EDIT_NICKNAME_FAILURE';

//비밀번호 변경
export const EDIT_PASSWORD_REQUEST = 'EDIT_PASSWORD_REQUEST';
export const EDIT_PASSWORD_SUCCESS = 'EDIT_PASSWORD_SUCCESS';
export const EDIT_PASSWORD_FAILURE = 'EDIT_PASSWORD_FAILURE';

// 게시글 업로드
export const POST_UPLOAD_REQUEST = 'POST_UPLOAD_REQUEST';
export const POST_UPLOAD_SUCCESS = 'POST_UPLOAD_SUCCESS';
export const POST_UPLOAD_FAILURE = 'POST_UPLOAD_FAILURE';

// 댓글 업로드
export const POST_COMMENT_REQUEST = 'POST_COMMENT_REQUEST';
export const POST_COMMENT_SUCCESS = 'POST_COMMENT_SUCCESS';
export const POST_COMMENT_FAILURE = 'POST_COMMENT_FAILURE';

//전체 게시글 로드
export const POST_LOAD_REQUEST = 'POST_LOAD_REQUEST';
export const POST_LOAD_SUCCESS = 'POST_LOAD_SUCCESS';
export const POST_LOAD_FAILURE = 'POST_LOAD_FAILURE';

//게시글 내용 로드
export const POST_DETAIL_LOAD_REQUEST = 'POST_DETAIL_LOAD_REQUEST';
export const POST_DETAIL_LOAD_SUCCESS = 'POST_DETAIL_LOAD_SUCCESS';
export const POST_DETAIL_LOAD_FAILURE = 'POST_DETAIL_LOAD_FAILURE';

// 카테고리별 게시글 로드

export const CATEGORY_POST_LOAD_REQUEST = 'CATEGORY_POST_LOAD_REQUEST';
export const CATEGORY_POST_LOAD_SUCCESS = 'CATEGORY_POST_LOAD_SUCCESS';
export const CATEGORY_POST_LOAD_FAILURE = 'CATEGORY_POST_LOAD_FAILURE';

//게시글 삭제
export const POST_DELETE_REQUEST = 'POST_DELETE_REQUEST';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';
export const POST_DELETE_FAILURE = 'POST_DELETE_FAILURE';

//게시글 추천 (up)
export const POST_UP_REQUEST = 'POST_UP_REQUEST';
export const POST_UP_SUCCESS = 'POST_UP_SUCCESS';
export const POST_UP_FAILURE = 'POST_UP_FAILURE';

//게시글 비추천 (down)

export const POST_DOWN_REQUEST = 'POST_DOWN_REQUEST';
export const POST_DOWN_SUCCESS = 'POST_DOWN_SUCCESS';
export const POST_DOWN_FAILURE = 'POST_DOWN_FAILURE';

//게시글 저장

export const POST_SAVE_REQUEST = 'POST_SAVE_REQUEST';
export const POST_SAVE_SUCCESS = 'POST_SAVE_SUCCESS';
export const POST_SAVE_FAILURE = 'POST_SAVE_FAILURE';
